### ISSUE TITLE
Eshell not working on windows

### ISSUE THREAD

**Issue by julian-hoch** [kyagi/shell-pop-el#72]
I use the same config on windows and linux:

```
(use-package shell-pop
  :config
  (setq shell-pop-shell-type '("eshell" "*eshell*" (lambda () (eshell))))
  (setq shell-pop-default-directory "~/")
  (setq shell-pop-autocd-to-working-dir t)
  (setq shell-pop-full-span t)
  :bind ("C-M-S-s" . shell-pop))
```

On linux this works and opens eshell, but on windows it opens the windows command line. Not sure whats going on, I can open eshell fine manually with M-x eshell on windows, too.

**Comment by syohex** [comment]
```lisp
(use-package shell-pop
  :config
  (custom-set-variables
   '(shell-pop-shell-type '("eshell" "*eshell*" (lambda () (eshell)))))
  (setq shell-pop-default-directory "~/")
  (setq shell-pop-autocd-to-working-dir t)
  (setq shell-pop-full-span t)
  :bind ("C-M-S-s" . shell-pop))
```

You have to use `custom-set-variables` instead of `setq` against `shell-pop-shell-type`. Because [the setter function](https://github.com/kyagi/shell-pop-el/blob/2741d275a6bb49f11814f2fda651c54b77eadf05/shell-pop.el#L134) should be called to reflect shell settings but the setter function is not called when using `setq`.

**Comment by julian-hoch** [comment]
Thanks! Learned something new, always appreciated.
